spring.application.name=ai-knowledge-assistant

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_knowledge_db
spring.datasource.username=postgres
spring.datasource.password=YOUR_PASSWORD

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3:latest
spring.ai.ollama.embedding.options.model=nomic-embed-text:latest

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.index-type=HNSW

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB